### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by vijaypm** [winslowdibona/csv-etl#1]
Hi Winslow,
This is a very useful utility and it would be great to clarify the license for this project. The pypi repository shows that the package is released under MIT. But, clarifying the license on the source would be better. 
Thanks.
Vijay

**Comment by winslowdibona** [comment]
@vijaypm done. Thanks for the suggestion.

**Comment by vijaypm** [comment]
Thank @winslowdibona
